### ISSUE TITLE
App crashes right after OF launching screen

### ISSUE THREAD

**Issue by Fritskee** [AndresCuervo/ofxARKit-example-facetracking#1]
Hi, 

I tried compiling and running the app on my iPhone (iPhone X with iOS 12.1), but each time I try getting it launched, the app crashes when the OF screen is shown on startup of the app.
According to this, I also set the Deployment Target on Xcode to 12.1, Devices are set to solely for iPhone and the automatic code signing is also on. 

I have completed the code signing through Apple, and I also allow the permissions to the app on my phone by allowing it the access under "settings >> general >> profiles" after Xcode "builds successfully" 

Any clue what could be wrong?

**Comment by Fritskee** [comment]
Sorry, managed to get it working.

Manually need to add a "Privacy Camera Usage Description" to the info.plist and the problem is solved!

**Comment by cwervo** [comment]
Glad you got this working, added the camera permission to the info.plist in the repo!
